# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3
pipelines:
  branches:
   '{master}':
    - step:
       name: 'Running Pipeline'
       script:
         - echo "Running Pipeline"
    - step:
        name: 'Deployment to Production'
        deployment: production
        trigger: 'manual'
        script:
          - echo "Pushing to Production..."
          - git push ssh://u1990-t22uxupo1hvw@gsgpm1047.siteground.biz:18765/home/customer/www/dticompass.dti.gov.ph/public_html/laravel/ master:master
   '{staging}':
    - step:
       name: 'Running Pipeline'
       script:
         - echo "Running Pipeline"
    - step:
        name: 'Deployment to Staging'
        trigger: 'manual'
        deployment: staging
        script:
          - echo "Pushing to Staging..."
          - git push ssh://u357-f31vucuafghn@gsgpm1049.siteground.biz:18765/home/customer/www/dticompass.razzaconsulting.com/public_html/laravel/ staging:master